mobile_robot:
        joints_update:
          type: joint_state_controller/JointStateController
          publish_rate: 30

        mobile_base_controller:
          type: "diff_drive_controller/DiffDriveController"
          left_wheel: 'left_wheel_joint'
          right_wheel: 'right_wheel_joint'
          publish_rate: 10.0
          pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
          twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

          wheel_separation: 0.193
          wheel_radius: 0.04

          wheel_separation_multiplier: 1.0
          wheel_radius_multiplier: 1.0

          cmd_vel_timeout: 0.1

          base_frame_id: "base_link"

          linear:
            x:
              has_velocity_limits : true
              max_velocity: 0.1
              min_velocity: -0.1
              has_acceleration_limits: true
              max_acceleration: 0.05
              min_acceleration: -0.05
              has_jerk_limits: false
              max_jerk: 0.0
          angular:
            z:
              has_velocity_limits : true
              max_velocity: 1.0472
              has_acceleration_limits: true
              max_acceleration: 0.1
              has_jerk_limits: false
              max_jerk: 0.0
